int reverseofnum(int);
int sumDigi(int num);
int occurence(int num);
int pali(int num);
int primi(int num);
int generate_first_n_prime_numbers(int);
int oneoneone(int lmt);
int strong(int num);
int ami(int a,int b);
int menu(int a,int b,int c);
void cube(int cubeside);
void cuboid(int l, int w, int h);
void sphere(float r);
void cylinder (float , float);
void cone (float radius, float height);
int electricitybill(int unit);
